version: 0.2
env:
  variables:
    stackName: "Strava2TwitterDev"
  parameter-store:
    pCodeBucket: "pStrava2twitterCodeBucket"
    pTwitterAccessTokenKey: "pTwitterAccessTokenKey"
    pTwitterAccessTokenSecret: "pTwitterAccessTokenSecret"
    pTwitterConsumerKey: "pTwitterConsumerKey"
    pTwitterConsumerSecret: "pTwitterConsumerSecret"
    pStravaClientId: "pStravaClientId"
    pStravaClientSecret: "pStravaClientSecret"
    pPushBullet: "pPushBullet"
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      # Package SAM template
      - sam build
      # Deploy packaged SAM template
      - sam deploy --stack-name $stackName --s3-bucket $pCodeBucket --capabilities "CAPABILITY_IAM" --parameter-overrides "ParameterKey=pStravaClientSecret,ParameterValue=$pStravaClientSecret ParameterKey=pStravaClientId,ParameterValue=$pStravaClientId ParameterKey=pTwitterAccessTokenKey,ParameterValue=$pTwitterAccessTokenKey ParameterKey=pTwitterAccessTokenSecret,ParameterValue=$pTwitterAccessTokenSecret ParameterKey=pTwitterConsumerKey,ParameterValue=$pTwitterConsumerKey ParameterKey=pTwitterConsumerSecret,ParameterValue=$pTwitterConsumerSecret"
      # Find out what the callback URL is from the stack
  post_build:
    commands:
      # Send a Pushbullet notification about the update to the stack
      - curl --silent -u """$pPushBullet"":" -d type="note" -d body="Updated $stackName" -d title="AWS Codebuild" 'https://api.pushbullet.com/v2/pushes'
