version: 0.2
env:
  variables:
    stackName: "Strava2TwitterDev"
    ssmPrefix: "p"
  parameter-store:
    pCodeBucket: "pStrava2twitterCodeBucket"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r src/layers/strava/src/python/requirements.txt
  pre_build:
    on-failure: ABORT
    commands:
      - python -m unittest discover -s test -p '*_test.py'
  build:
    on-failure: ABORT
    commands:
      # Package SAM template
      - sam build
  post_build:
    commands:
      - echo "Deploy"
      - sam deploy --stack-name $stackName --s3-bucket $pCodeBucket --capabilities "CAPABILITY_IAM" --parameter-overrides "ParameterKey=pSSMPrefix,ParameterValue=$ssmPrefix"
