version: 0.2
env:
  variables:
    stackName: "Strava2TwitterDev"
  parameter-store:
    pCodeBucket: "pStrava2twitterCodeBucket"
    pTwitterAccessTokenKey: "pTwitterAccessTokenKey"
    pTwitterAccessTokenSecret: "pTwitterAccessTokenSecret"
    pTwitterConsumerKey: "pTwitterConsumerKey"
    pTwitterConsumerSecret: "pTwitterConsumerSecret"
    pStravaClientId: "pStravaClientId"
    pStravaClientSecret: "pStravaClientSecret"
    pPushBullet: "pPushBullet"
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template
      - sam build
      # Deploy packaged SAM template
      - sam deploy --stack-name $stackName --s3-bucket $pCodeBucket --capabilities "CAPABILITY_IAM" --parameter-overrides "ParameterKey=pStravaClientSecret,ParameterValue=$pStravaClientSecret ParameterKey=pStravaClientId,ParameterValue=$pStravaClientId ParameterKey=pTwitterAccessTokenKey,ParameterValue=$pTwitterAccessTokenKey ParameterKey=pTwitterAccessTokenSecret,ParameterValue=$pTwitterAccessTokenSecret ParameterKey=pTwitterConsumerKey,ParameterValue=$pTwitterConsumerKey ParameterKey=pTwitterConsumerSecret,ParameterValue=$pTwitterConsumerSecret"
      # Find out what the callback URL is from the stack
      - APIGwId=$(aws cloudformation describe-stack-resources --stack-name $stackName --logical-resource-id="ServerlessHttpApi" --query "StackResources[0].PhysicalResourceId" --output text)
      - CallbackURL="https://$APIGwId.execute-api.$AWS_REGION.amazonaws.com/webhook/"
      # Register the webhook with Strava
      - curl -X POST https://www.strava.com/api/v3/push_subscriptions -F client_id=$pStravaClientId -F client_secret=$pStravaClientSecret -F "callback_url=$CallbackURL" -F "verify_token=STRAVA"
      # Send a Pushbullet notification about the update to the stack
      - curl --silent -u """$pPushBullet"":" -d type="note" -d body="Updated $stackName" -d title="AWS Codebuild" 'https://api.pushbullet.com/v2/pushes'
