version: 0.2
env:
  variables:
    pStravaName: "Jonathan Jenkyn"
  parameter-store:
    pTwitterAccessTokenKey: "pTwitterAccessTokenKey"
    pTwitterAccessTokenSecret: "pTwitterAccessTokenSecret"
    pTwitterConsumerKey: "pTwitterConsumerKey"
    pTwitterConsumerSecret: "pTwitterConsumerSecret"
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template
      - sam build
      # Deploy packaged SAM template
      - sam deploy --stack-name 'Strava2TwitterAuto' --s3-bucket "strava2twittercode" --parameter-overrides 'ParameterKey=pStravaName,ParameterValue=$pStravaName ParameterKey=pTwitterAccessTokenKey,ParameterValue=$pTwitterAccessTokenKey ParameterKey=pTwitterAccessTokenSecret,ParameterValue=$pTwitterAccessTokenSecret ParameterKey=pTwitterConsumerKey,ParameterValue=$pTwitterConsumerKey ParameterKey=pTwitterConsumerSecret,ParameterValue=$pTwitterConsumerSecret'
      - echo Done `date`
