# Copyright 2020 Jonathan Jenkyn
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'StravaToTwitterProxy'

###
### CloudFormation Interface Metadata
###

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Configuration
      Parameters:
      - pTwitterConsumerKey
      - pTwitterConsumerSecret
      - pTwitterAccessTokenKey
      - pTwitterAccessTokenSecret
    ParameterLabels:
      pTwitterConsumerKey:
        default: Twitter Consumer Key
      pTwitterConsumerSecret:
        default: Twitter Consumer Secret
      pTwitterAccessTokenKey:
        default: Twitter Access Token Key
      pTwitterAccessTokenSecret:
        default: Twitter Access Token Secret

###
### Template input parameters
###

Parameters:
  pTwitterConsumerKey:
    Type: String
    Description: The Twitter Consumer Key (Get this from the Twitter Developer Dashboard)
  pTwitterConsumerSecret:
    Type: String
    Description: The Twitter Consumer Secret (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenKey:
    Type: String
    Description: The Twitter Access Token Key (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenSecret:
    Type: String
    Description: The Twitter Access Token Secret (Get this from the Twitter Developer Dashboard)

###
### Template Resources
###

Resources:

  # Our lambda function
  rLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: lambda_function.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          twitterConsumerKey: !Ref pTwitterConsumerKey
          twitterConsumerSecret: !Ref pTwitterConsumerSecret
          twitterAccessTokenKey: !Ref pTwitterAccessTokenKey
          twitterAccessTokenSecret: !Ref pTwitterAccessTokenSecret
      Events:
        postRun:
          Type: Api
          Properties:
            RestApiId: !Ref APIGw
            Path: /
            Method: POST

  APIGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"

Outputs:
  ApiUrl:
      Description: "API endpoint URL for Prod environment"
      Value: !Sub 'https://${APIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
      