# Copyright 2020 Jonathan Jenkyn
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'StravaToTwitter'

###
### Template input parameters
###

Parameters:
  pTwitterConsumerKey:
    Type: String
    Description: The Twitter Consumer Key (Get this from the Twitter Developer Dashboard)
  pTwitterConsumerSecret:
    Type: String
    Description: The Twitter Consumer Secret (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenKey:
    Type: String
    Description: The Twitter Access Token Key (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenSecret:
    Type: String
    Description: The Twitter Access Token Secret (Get this from the Twitter Developer Dashboard)
  pStravaClientId:
    Type: String
    Description: The Client Id for this application.
  pStravaClientSecret:
    Type: String
    Description: The Client Secret for this application

Mappings:
  BotoVendArnMap:
    ap-northeast-1:
      layerArn: "arn:aws:lambda:ap-northeast-1:249908578461:layer:AWSLambda-Python-AWS-SDK:4"
    us-east-1:
      layerArn: "arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4"
    ap-southeast-1:
      layerArn: "arn:aws:lambda:ap-southeast-1:468957933125:layer:AWSLambda-Python-AWS-SDK:4"
    eu-west-1:
      layerArn: "arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python-AWS-SDK:4"
    us-west-1:
      layerArn: "arn:aws:lambda:us-west-1:325793726646:layer:AWSLambda-Python-AWS-SDK:4"
    ap-east-1:
      layerArn: "arn:aws:lambda:ap-east-1:118857876118:layer:AWSLambda-Python-AWS-SDK:4"
    ap-northeast-2:
      layerArn: "arn:aws:lambda:ap-northeast-2:296580773974:layer:AWSLambda-Python-AWS-SDK:4"
    ap-northeast-3:
      layerArn: "arn:aws:lambda:ap-northeast-3:961244031340:layer:AWSLambda-Python-AWS-SDK:4"
    ap-south-1:
      layerArn: "arn:aws:lambda:ap-south-1:631267018583:layer:AWSLambda-Python-AWS-SDK:4"
    ap-southeast-2:
      layerArn: "arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python-AWS-SDK:4"
    ca-central-1:
      layerArn: "arn:aws:lambda:ca-central-1:778625758767:layer:AWSLambda-Python-AWS-SDK:4"
    eu-central-1:
      layerArn: "arn:aws:lambda:eu-central-1:292169987271:layer:AWSLambda-Python-AWS-SDK:4"
    eu-north-1:
      layerArn: "arn:aws:lambda:eu-north-1:642425348156:layer:AWSLambda-Python-AWS-SDK:4"
    eu-west-2:
      layerArn: "arn:aws:lambda:eu-west-2:142628438157:layer:AWSLambda-Python-AWS-SDK:4"
    eu-west-3:
      layerArn: "arn:aws:lambda:eu-west-3:959311844005:layer:AWSLambda-Python-AWS-SDK:4"
    sa-east-1:
      layerArn: "arn:aws:lambda:sa-east-1:640010853179:layer:AWSLambda-Python-AWS-SDK:4"
    us-east-2:
      layerArn: "arn:aws:lambda:us-east-2:259788987135:layer:AWSLambda-Python-AWS-SDK:4"
    us-west-2:
      layerArn: "arn:aws:lambda:us-west-2:420165488524:layer:AWSLambda-Python-AWS-SDK:5"
    cn-north-1:
      layerArn: "arn:aws-cn:lambda:cn-north-1:683298794825:layer:AWSLambda-Python-AWS-SDK:4"
    cn-northwest-1:
      layerArn: "arn:aws-cn:lambda:cn-northwest-1:382066503313:layer:AWSLambda-Python-AWS-SDK:4"
    us-gov-west:
      layerArn: "arn:aws-us-gov:lambda:us-gov-west-1:556739011827:layer:AWSLambda-Python-AWS-SDK:4"
    us-gov-east:
      layerArn: "arn:aws-us-gov:lambda:us-gov-east-1:138526772879:layer:AWSLambda-Python-AWS-SDK:4"
###
### Template Resources
###

Resources:

  ProxyLambdaFunction:
    DependsOn: 
    - Totals
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: proxy.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          twitterConsumerKey: !Ref pTwitterConsumerKey
          twitterConsumerSecret: !Ref pTwitterConsumerSecret
          twitterAccessTokenKey: !Ref pTwitterAccessTokenKey
          twitterAccessTokenSecret: !Ref pTwitterAccessTokenSecret
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref pStravaClientSecret
          totalsTable: !Ref Totals
          webhookASync: !Ref WebhookASync
      Events:
        HttpApiEvent:
          Type: HttpApi

      Policies:
      - Statement:
        - Sid: LambdaInvoke
          Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: !GetAtt WebhookASync.Arn
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:PutItem
          Resource: !GetAtt Totals.Arn
  # Our lambda function

  WebhookASync:
    DependsOn: 
    - Totals
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: webhookasync.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref pStravaClientSecret
          totalsTable: !Ref Totals
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          Resource: !GetAtt Totals.Arn

  Totals:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
  GetAPIAddressLambda:
    DependsOn: 
    - ProxyLambdaFunction
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 10
      Handler: index.lambda_handler
      Layers:
        - !FindInMap [BotoVendArnMap,!Ref "AWS::Region", layerArn]
      InlineCode: |
        import json, boto3, os
        from botocore.vendored import requests
 
        SUCCESS = "SUCCESS"
        FAILED = "FAILED"
         
        def send(event, context, responseStatus, responseData, physicalResourceId=None, noEcho=False):
            responseUrl = event['ResponseURL']
         
            print(responseUrl)
         
            responseBody = {}
            responseBody['Status'] = responseStatus
            responseBody['Reason'] = 'See the details in CloudWatch Log Stream: ' + context.log_stream_name
            responseBody['PhysicalResourceId'] = physicalResourceId or context.log_stream_name
            responseBody['StackId'] = event['StackId']
            responseBody['RequestId'] = event['RequestId']
            responseBody['LogicalResourceId'] = event['LogicalResourceId']
            responseBody['NoEcho'] = noEcho
            responseBody['Data'] = responseData
        
        def lambda_handler(event, context):
          cfn=boto3.client("cloudformation")
          ServerlessHttpApi=cfn.describe_stack_resource(
              StackName=os.environ['StackName'],
              LogicalResourceId="ServerlessHttpApi"
          )
          BASEURL="https://{RESOURCEID}.execute-api.{REGION}.amazonaws.com/".format(RESOURCEID=ServerlessHttpApi["StackResourceDetail"]['PhysicalResourceId'],REGION=boto3.session.Session().region_name)
          data = {
            "webhook" : "{BASEURL}webhook/".format(BASEURL=BASEURL),
            "register": "{BASEURL}register/".format(BASEURL=BASEURL)
          }
          send(event, context, SUCCESS, data)
          
      Policies:
      - Statement:
        - Sid: CloudFormationAccess
          Effect: Allow
          Action:
          - cloudformation:DescribeStackResource
          Resource: !Ref "AWS::StackId"
        
  GetAPIAddress:
    Type: 'Custom::APIAddress'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt GetAPIAddressLambda.Arn
      StackName: !Ref "AWS::StackName"
Outputs:
  WebhookURL:
    Description: This is the URL that you need to set up the callback. This is called the callback URL in Strava parlance
    Value: !GetAtt GetAPIAddress.webhook
  RegisterURL:
    Description: This is the URL that users will use to register with you through their Strava account
    Value: !GetAtt GetAPIAddress.register