# Copyright 2020 Jonathan Jenkyn
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'StravaToTwitter'

###
### Template input parameters
###

Parameters:
  pTwitterConsumerKey:
    Type: String
    Description: The Twitter Consumer Key (Get this from the Twitter Developer Dashboard)
  pTwitterConsumerSecret:
    Type: String
    Description: The Twitter Consumer Secret (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenKey:
    Type: String
    Description: The Twitter Access Token Key (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenSecret:
    Type: String
    Description: The Twitter Access Token Secret (Get this from the Twitter Developer Dashboard)
  pStravaClientId:
    Type: String
    Description: The Client Id for this application.
  pStravaClientSecret:
    Type: String
    Description: The Client Secret for this application

###
### Template Resources
###

Resources:

  # Our lambda function
  rRegisterFunction:
    DependsOn: 
    - RegisterAPIGw
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: register.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          stravaClientId: !Ref pStravaClientId
          stackID: !Ref "AWS::StackName"
      Events:
        register:
          Type: Api
          Properties:
            RestApiId: !Ref RegisterAPIGw
            Path: /register
            Method: GET
      Policies:
      - Statement:
        - Sid: CloudformationAccess
          Effect: Allow
          Action:
          - cloudformation:DescribeStacks
          Resource: !Ref "AWS::StackId"

  rRegisterSuccessFunction:
    DependsOn: 
    - RegisterSuccessAPIGw
    - Totals
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: registersuccess.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          twitterConsumerKey: !Ref pTwitterConsumerKey
          twitterConsumerSecret: !Ref pTwitterConsumerSecret
          twitterAccessTokenKey: !Ref pTwitterAccessTokenKey
          twitterAccessTokenSecret: !Ref pTwitterAccessTokenSecret
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref pStravaClientSecret
          totalsTable: !Ref Totals
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:PutItem
          Resource: !GetAtt Totals.Arn
      Events:
        registersuccess:
          Type: Api
          Properties:
            RestApiId: !Ref RegisterSuccessAPIGw
            Path: /registersuccess
            Method: GET

  rWebhookFunction:
    DependsOn: 
    - rWebhookASync
    - WebhookAPIGw
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: webhook.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          ASyncLambda: !Ref rWebhookASync
      Policies:
      - Statement:
        - Sid: LambdaInvoke
          Effect: Allow
          Action:
          - lambda:Invoke
          Resource: !GetAtt rWebhookASync.Arn
      Events:
        webhookpost:
          Type: Api
          Properties:
            RestApiId: !Ref WebhookAPIGw
            Path: /webhook
            Method: POST
        webhookget:
          Type: Api
          Properties:
            RestApiId: !Ref WebhookAPIGw
            Path: /webhook
            Method: GET
  
  rWebhookASync:
    DependsOn: 
    - Totals
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: webhookasync.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref pStravaClientSecret
          totalsTable: !Ref Totals
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          Resource: !GetAtt Totals.Arn

  RegisterAPIGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  
  RegisterSuccessAPIGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  
  WebhookAPIGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  
  Totals:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  RegisterUrl:
      Description: "URL to register"
      Value: !Sub 'https://${RegisterAPIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/register'
  RegisterSuccessUrl:
      Description: "URL for registration success"
      Value: !Sub 'https://${RegisterSuccessAPIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/registersuccess'
  CallbackUrl:
      Description: "URL of webhook"
      Value: !Sub 'https://${WebhookAPIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook'