# Copyright 2020 Jonathan Jenkyn
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'StravaToTwitter'

###
### Template input parameters
###

Parameters:
  pTwitterConsumerKey:
    Type: String
    Description: The Twitter Consumer Key (Get this from the Twitter Developer Dashboard)
  pTwitterConsumerSecret:
    Type: String
    Description: The Twitter Consumer Secret (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenKey:
    Type: String
    Description: The Twitter Access Token Key (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenSecret:
    Type: String
    Description: The Twitter Access Token Secret (Get this from the Twitter Developer Dashboard)
  pStravaClientId:
    Type: String
    Description: The Client Id for this application.
  pStravaClientSecret:
    Type: String
    Description: The Client Secret for this application

###
### Template Resources
###

Resources:

  ProxyLambdaFunction:
    DependsOn: 
    - Totals
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: proxy.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          twitterConsumerKey: !Ref pTwitterConsumerKey
          twitterConsumerSecret: !Ref pTwitterConsumerSecret
          twitterAccessTokenKey: !Ref pTwitterAccessTokenKey
          twitterAccessTokenSecret: !Ref pTwitterAccessTokenSecret
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref pStravaClientSecret
          totalsTable: !Ref Totals
          webhookASync: !Ref WebhookASync
      Events:
        HttpApiEvent:
          Type: HttpApi

      Policies:
      - Statement:
        - Sid: LambdaInvoke
          Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: !GetAtt WebhookASync.Arn
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:PutItem
          Resource: !GetAtt Totals.Arn
  # Our lambda function

  WebhookASync:
    DependsOn: 
    - Totals
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: webhookasync.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref pStravaClientSecret
          totalsTable: !Ref Totals
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          Resource: !GetAtt Totals.Arn

  Totals:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
  GetAPIAddressLambda:
    DependsOn: 
    - ProxyLambdaFunction
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: index.lambda_handler
      InlineCode: |
        import json, boto3, cfnresponse
        
        def lambda_handler(event, context):
          cfn=boto3.client("cloudformation")
          ServerlessHttpApi=cfn.describe_stack_resource(
              StackName=os.environ['StackName'],
              LogicalResourceId="ServerlessHttpApi"
          )
          BASEURL="https://{RESOURCEID}.execute-api.{REGION}.amazonaws.com/".format(RESOURCEID=ServerlessHttpApi["StackResourceDetail"]['PhysicalResourceId'],REGION=boto3.session.Session().region_name)
          data = {
            "webhook" : "{BASEURL}webhook/".format(BASEURL=BASEURL),
            "register": "{BASEURL}register/".format(BASEURL=BASEURL)
          }
          cfnresponse.send(event, context, cfnresponse.SUCCESS, data, "CustomResourcePhysicalID")
          
      Policies:
      - Statement:
        - Sid: CloudFormationAccess
          Effect: Allow
          Action:
          - cloudformation:DescribeStackResource
          Resource: !Ref "AWS::StackID"
        
  GetAPIAddress:
    Type: 'Custom::APIAddress'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt GetAPIAddressLambda.Arn
      StackName: !Ref "AWS::StackName"
Outputs:
  WebhookURL:
    Description: This is the URL that you need to set up the callback. This is called the callback URL in Strava parlance
    Value: !GetAtt GetAPIAddress.webhook
  RegisterURL:
    Description: This is the URL that users will use to register with you through their Strava account
    Value: !GetAtt GetAPIAddress.register