# Copyright 2020 Jonathan Jenkyn
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'StravaToTwitter'

###
### Template input parameters
###

Parameters:
  pTwitterConsumerKey:
    Type: String
    Description: The Twitter Consumer Key (Get this from the Twitter Developer Dashboard)
  pTwitterConsumerSecret:
    Type: String
    Description: The Twitter Consumer Secret (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenKey:
    Type: String
    Description: The Twitter Access Token Key (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenSecret:
    Type: String
    Description: The Twitter Access Token Secret (Get this from the Twitter Developer Dashboard)
  pStravaClientId:
    Type: String
    Description: The Client Id for this application.
  pStravaClientSecret:
    Type: String
    Description: The Client Secret for this application

###
### Template Resources
###

Resources:

  # Our lambda function
  rRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: register.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          stravaClientId: !Ref pStravaClientId
          stravaRedirect: !Sub 'https://${APIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/registersuccess'
      Events:
        register:
          Type: Api
          Properties:
            RestApiId: !Ref APIGw
            Path: /register
            Method: GET

  rRegisterCompleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: registersuccess.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref StravaClientSecret
          totalsTable: !Ref Totals
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          Resource: !GetAtt Totals.Arn
      Events:
        registesuccess:
          Type: Api
          Properties:
            RestApiId: !Ref APIGw
            Path: /registersuccess
            Method: GET

  rWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 60
      Handler: webhook.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          twitterConsumerKey: !Ref pTwitterConsumerKey
          twitterConsumerSecret: !Ref pTwitterConsumerSecret
          twitterAccessTokenKey: !Ref pTwitterAccessTokenKey
          twitterAccessTokenSecret: !Ref pTwitterAccessTokenSecret
          stravaClientId: !Ref pStravaClientId
          stravaClientSecret: !Ref StravaClientSecret
          totalsTable: !Ref Totals
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          Resource: !GetAtt Totals.Arn
      Events:
        webhookpost:
          Type: Api
          Properties:
            RestApiId: !Ref APIGw
            Path: /webhook
            Method: POST
        webhookget:
          Type: Api
          Properties:
            RestApiId: !Ref APIGw
            Path: /webhook
            Method: GET
          

  APIGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  
  Totals:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  RegisterUrl:
      Description: "URL to register"
      Value: !Sub 'https://${APIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/register'
  CallbackUrl:
      Description: "URL to register"
      Value: !Sub 'https://${APIGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook'